---
title: "HUANG"
format: html
editor: visual
---
```{r}
here::i_am("grades-test.Rproj")
```

```{r}
library(here)
library(vroom)
library(dplyr)
library(ggplot2)
library(tidyr)
library(knitr)
```

# Q1 Load data
```{r}
courses <- vroom(here("data","courses.csv"))
```


# Q2 Formatted table

```{r}
courses |>
  arrange(courses) |>
  kable(
    caption = "List of courses",
    align   = "l"
  )
```


# Q3 Load Students dataset

```{r}

students <- vroom(
  here("data", "students.csv"),
  col_types = cols(
    id         = col_integer(),
    group      = col_factor(),
    birth_date = col_date(),
    sex        = col_factor()
  )
)
```

# Q4 Load grades dataset 

```{r}
grades <- vroom(
  here("data", "grades.csv"),
  delim = ":",
  na    = "*"
)
```

# Q5 Number of students per group

```{r}
students |>
  count(group, name = "n_students") |>
  ggplot(aes(x = group, y = n_students)) +
  geom_col() +
  labs(
    title = "Number of students per group",
    x = "Group",
    y = "Number of students"
  ) +
  theme_minimal()
```

# Q6 Gender balance in each group

```{r}
students |>
  ggplot(aes(x = group, fill = sex)) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(
    title = "Gender balance by group",
    x = "Group",
    y = "Share of students",
    fill = "Sex"
  ) +
  theme_minimal()
```

# Q7 Distribution of the age of the student
```{r}
students_age <- students |>
  mutate(
    age = as.numeric(difftime(Sys.Date(), birth_date, units = "days")) / 365.25
  )

students_age |>
  ggplot(aes(x = age)) +
  geom_histogram(binwidth = 1) +
  labs(
    title = "Distribution of students' age",
    x = "Age (years)",
    y = "Number of students"
  ) +
  theme_minimal()
```


# Q8 Median age of each student in each group
```{r}
median_age_by_group <- students_age |>
  group_by(group) |>
  summarise(
    median_age = as.integer(round(median(age, na.rm = TRUE))),
    .groups = "drop"
  )

median_age_by_group |>
  kable(
    caption = "Median age of students by group",
    col.names = c("Group", "Median age")
  )
```

# Q9 Oldest student in each group
```{r}
oldest_by_group <- students_age |>
  group_by(group) |>
  slice_max(age, n = 1, with_ties = FALSE) |>
  ungroup() |>
  arrange(desc(age)) |>
  transmute(
    id,
    sex,
    age = round(age, 1) 
  )


oldest_by_group |>
  kable(
    caption   = "Oldest student in each group",
    col.names = c("ID", "Sex", "Age")
  )
```

# Q10 Number of grades in the dataset
```{r}
nb_grades <- grades |>
  filter(!is.na(grade)) |>
  nrow()
```

The data set contains `r nb_grades` grades.


# Q11 
